In [1]:
from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = "all"

In [2]:
import hopsworks

In [ ]:
import os
from dotenv import dotenv_values
ENV = dotenv_values("./work/AIEngineering/machine_learning/feature_store/hopsworks/.env")

In [59]:
project = hopsworks.login(
    project='my_first_project10',  
    host="eu-west.cloud.hopsworks.ai",
    port=443,
    api_key_value=ENV['api_key']
)

2026-09-15 19:09:45,665 INFO: Closing external client and cleaning up certificates.
2026-09-15 19:09:45,709 INFO: Connection closed.
2026-09-15 19:09:45,712 INFO: Initializing external client
2026-09-15 19:09:45,713 INFO: Base URL: https://eu-west.cloud.hopsworks.ai:443
2026-09-15 19:09:48,467 INFO: Python Engine initialized.

Logged in to project, explore it here https://eu-west.cloud.hopsworks.ai:443/p/42213

In [ ]:
fs = project.get_feature_store()

In [17]:
!ls work/AIEngineering/machine_learning/feature_store/hopsworks/get_feature_vector/dados/

customers-100.csv

In [44]:
import pandas as pd

df_customers = pd.read_csv('./work/AIEngineering/machine_learning/feature_store/hopsworks/get_feature_vector/dados/customers-100.csv')
df_customers

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

## Read csv

In [51]:
entity_person_score = pd.read_csv('./work/AIEngineering/machine_learning/feature_store/hopsworks/get_feature_vector/dados/person_score.csv')

entity_person_score

,entity_id,timestamp,feature_idade,feature_score_credito,feature_total_compras_30d,feature_status_premium
0,usr_001,2023-09-13T12:00:00Z,28,720,100.50,1
1,usr_002,2024-04-13T12:05:00Z,45,610,0.00,0
2,usr_003,2025-03-19T12:10:00Z,32,840,520.99,1
3,usr_004,2026-03-12T12:15:00Z,19,550,25.00,0
4,usr_001,2026-03-12T12:00:00Z,28,740,130.50,1
5,usr_001,2026-09-10T12:00:00Z,28,750,150.50,0

In [77]:
entity_person_complaints = pd.read_csv('./work/AIEngineering/machine_learning/feature_store/hopsworks/get_feature_vector/dados/person_complaints.csv')

entity_person_complaints

,entity_id,timestamp,feature_categoria_favorita,feature_tempo_logado_min,feature_dispositivo_principal,feature_reclamacoes_abertas
0,usr_001,2025-09-15T13:00:00Z,Eletrônicos,145.2,Mobile,0
1,usr_002,2023-01-15T13:00:00Z,Moda,12.0,Desktop,1
2,usr_003,2026-03-15T13:00:00Z,Casa e Decor,310.5,Mobile,0
3,usr_004,2026-04-15T13:00:00Z,Games,45.8,Console,2
4,usr_001,2026-03-15T13:00:00Z,Eletrônicos,300.2,Mobile,1
5,usr_004,2026-05-15T13:00:00Z,Games,100.8,Console,4
6,usr_001,2026-09-15T13:00:00Z,Eletrônicos,300.2,Mobile,3

## Feature Groups

### Criação de features groups e inserindo dataframe nas features groups - lendo dados de um feature group

In [55]:
person_score_fg = fs.get_or_create_feature_group(
    name="score_credito",
    version=3,
    primary_key=["entity_id"],
    description="Comportamento financeiro e de engajamento da entidade Pessoa",
    online_enabled=True,
)
entity_person_score['timestamp'] = pd.to_datetime(entity_person_score['timestamp'])
person_score_fg.insert(entity_person_score)

Feature Group created successfully, explore it at
https://eu-west.cloud.hopsworks.ai:443/p/42213/fs/30898/fg/52643

UserWarning: Casting timestamp column 'timestamp' from 'ns' to 'us' will lose precision.
Uploading Dataframe: 100.00% |██████████| Rows 6/6 | Elapsed Time: 00:01 | Remaining Time: 00:00

(None, None)

In [60]:
fs.get_feature_group(
    name="score_credito",
    version=3
).read(online=True)

,entity_id,timestamp,feature_idade,feature_score_credito,feature_total_compras_30d,feature_status_premium
0,usr_002,2024-04-13 12:05:00,45,610,0.00,0
1,usr_001,2026-09-10 12:00:00,28,750,150.50,0
2,usr_004,2026-03-12 12:15:00,19,550,25.00,0
3,usr_003,2025-03-19 12:10:00,32,840,520.99,1

In [78]:
person_complaints_fg = fs.get_or_create_feature_group(
    name="complaints",
    version=3,
    primary_key=["entity_id"],
    description="Reclamcaoes, tempo logado, dispositivo principal da  entidade Pessoa",
    online_enabled=True
)
entity_person_complaints['timestamp'] = pd.to_datetime(entity_person_complaints['timestamp'])
person_complaints_fg.insert(entity_person_complaints)

UserWarning: Casting timestamp column 'timestamp' from 'ns' to 'us' will lose precision.
Uploading Dataframe: 100.00% |██████████| Rows 7/7 | Elapsed Time: 00:02 | Remaining Time: 00:00

(None, None)

In [31]:
fs.get_feature_group(
    name="complaints",
    version=1
).read()

Finished: Reading data from Hopsworks, using Hopsworks Feature Query Service (1.54s)

,entity_id,timestamp,feature_categoria_favorita,feature_tempo_logado_min,feature_dispositivo_principal,feature_reclamacoes_abertas
0,usr_001,2026-09-15T13:00:00Z,Eletrônicos,145.2,Mobile,0
1,usr_002,2026-09-15T13:00:00Z,Moda,12.0,Desktop,1
2,usr_003,2026-09-15T13:00:00Z,Casa e Decor,310.5,Mobile,0
3,usr_004,2026-09-15T13:00:00Z,Games,45.8,Console,2

In [62]:
fg_score_credito = fs.get_feature_group(
    name="score_credito",
    version=3
)


fg_complaints = fs.get_feature_group(
    name="complaints",
    version=3
)

In [ ]:
# Read data from the feature group
df = fg.read()
print(f"Connected to {project.name}. Feature group has {len(df)} rows")

# For model serving
ms = project.get_model_serving()

# For model registry
mr = project.get_model_registry()

###  Trazendo todas as features armazenadas da features groups

In [33]:
all_fgs = fs.get_feature_groups()

In [34]:
for fg in all_fgs:
  print(f"Nome: {fg.name}, Versão: {fg.version}")

Nome: pessoa_comportamento_identitario, Versão: 1
Nome: score_credito, Versão: 1
Nome: pessoa_comportamento_financeiro, Versão: 2
Nome: pessoa_comportamento_financeiro_plus, Versão: 2
Nome: pessoa_comportamento_financeiro_plus, Versão: 1
Nome: complaints, Versão: 1
Nome: pessoa_comportamento_cadeira, Versão: 2
Nome: pessoa_comportamento_cadeira, Versão: 3
Nome: pessoa_comportamento_financeiro, Versão: 1
Nome: pessoa_comportamento_identitario, Versão: 2
Nome: pessoa_comportamento_cadeira, Versão: 4

##  Feature View

In [ ]:
fg_score_credito.select_all().read(online=True)

Finished: Reading data from Hopsworks, using Hopsworks Feature Query Service (6.64s)

,entity_id,timestamp,feature_idade,feature_score_credito,feature_total_compras_30d,feature_status_premium
0,usr_001,2023-09-13T12:00:00Z,28,720,100.50,1
1,usr_002,2024-04-13T12:05:00Z,45,610,0.00,0
2,usr_003,2025-03-19T12:10:00Z,32,840,520.99,1
3,usr_004,2026-03-12T12:15:00Z,19,550,25.00,0
4,usr_001,2026-03-12T12:00:00Z,28,740,130.50,1
5,usr_001,2026-09-10T12:00:00Z,28,750,150.50,0

In [39]:
fg_complaints.select_all().read()

Finished: Reading data from Hopsworks, using Hopsworks Feature Query Service (3.73s)

,entity_id,timestamp,feature_categoria_favorita,feature_tempo_logado_min,feature_dispositivo_principal,feature_reclamacoes_abertas
0,usr_001,2026-09-15T13:00:00Z,Eletrônicos,145.2,Mobile,0
1,usr_002,2026-09-15T13:00:00Z,Moda,12.0,Desktop,1
2,usr_003,2026-09-15T13:00:00Z,Casa e Decor,310.5,Mobile,0
3,usr_004,2026-09-15T13:00:00Z,Games,45.8,Console,2

### Usando o select_all() para a construção de uma feature view

In [ ]:
query_features_all = fg_score_credito.select_all() \
    .join(fg_complaints.select_all())

In [ ]:
feature_view = fs.create_feature_view(
    name="modelo_score_complaints",
    version=4,
    labels=["feature_reclamacoes_abertas"],
    query=query_features
)

In [ ]:
feature_view = fs.get_feature_view(name="modelo_score_complaints", version=4)

In [ ]:
feature_vector = feature_view.get_feature_vector({"entity_id": "usr_001"})

VersionWarning: No training dataset version was provided to initialise serving. Defaulting to version 1.

In [ ]:
feature_vector

['usr_001',
 datetime.datetime(2026, 9, 10, 12, 0),
 28,
 750,
 150.5,
 0,
 'usr_001',
 datetime.datetime(2026, 9, 15, 13, 0),
 'Eletrônicos',
 300.2,
 'Mobile']

### Selecionando features e construindo uma feature view

In [70]:
query_features_select = fg_score_credito \
    .select(["feature_idade", "feature_score_credito", "feature_total_compras_30d", "feature_status_premium"]) \
        .join(fg_complaints.select(["feature_categoria_favorita", "feature_tempo_logado_min", "feature_dispositivo_principal","feature_reclamacoes_abertas"]))

In [71]:
feature_view = fs.create_feature_view(
    name="modelo_score_complaints",
    version=5,
    labels=["feature_reclamacoes_abertas"],
    query=query_features_select,
    description="Feature view com select"
)

Feature view created successfully, explore it at
https://eu-west.cloud.hopsworks.ai:443/p/42213/fs/30898/fv/modelo_score_complaints/version/5

### Pegando a feature view versao 5 com a selecao de features especificas

In [72]:
feature_view = fs.get_feature_view(name="modelo_score_complaints", version=5)

In [73]:
feature_vector = feature_view.get_feature_vector({"entity_id": "usr_001"})

VersionWarning: No training dataset version was provided to initialise serving. Defaulting to version 1.

In [74]:
feature_vector

[28, 750, 150.5, 0, 'Eletrônicos', 300.2, 'Mobile']

In [ ]:
fg_score_credito.read()

Finished: Reading data from Hopsworks, using Hopsworks Feature Query Service (1.60s)

,entity_id,timestamp,feature_idade,feature_score_credito,feature_total_compras_30d,feature_status_premium
0,usr_001,2023-09-13 12:00:00,28,720,100.50,1
1,usr_002,2024-04-13 12:05:00,45,610,0.00,0
2,usr_003,2025-03-19 12:10:00,32,840,520.99,1
3,usr_004,2026-03-12 12:15:00,19,550,25.00,0
4,usr_001,2026-03-12 12:00:00,28,740,130.50,1
5,usr_001,2026-09-10 12:00:00,28,750,150.50,0

In [ ]:
fg_score_credito.read()

In [37]:
feature_vectors = feature_view.get_feature_vectors(
    entry=[{"pessoa_id": 1001}, {"pessoa_id": 1002}, {"pessoa_id":1001}]
)
feature_vectors

[[1001, 28, 1, 2000.0, '2025-05', 110, 1],
 [1002, 45, 5, 8500.0, '2026-01', 68, 2],
 [1001, 28, 1, 2000.0, '2025-05', 110, 1]]

### Metodo offline (batch) training dataset

In [38]:
X_train, X_test, y_train, y_test = feature_view.train_test_split(
    test_size=0.2,
    description="Dataset para treino do modelo de risco v1"
)

2026-09-03 16:59:52,220 INFO: Computing insert statistics
2026-09-03 16:59:52,232 INFO: Computing insert statistics

Finished: Reading data from Hopsworks, using Hopsworks Feature Query Service (3.58s)

VersionWarning: Incremented version to `1`.

In [39]:
X_train

,pessoa_id,idade,dias_desde_ultimo_login,gastos_100d,timestamp,peso,quantos_dias_sem_comer
0,1001,28,1,1200.0,2025-03,110,1
1,1002,45,5,8500.0,2026-01,68,2
3,1001,28,1,2000.0,2025-05,110,1
4,1004,19,0,NaN,None,62,3

In [ ]:
df
feature_vectors = feature_view.get_feature_vectors(
    entry=[{"pessoa_id": 1001}, {"pessoa_id": 1002}, {"pessoa_id":1001}],
    passed_features=[{"idade":30}, {"idade":33}, {"idade":46}]
)
feature_vectors

,pessoa_id,idade,dias_desde_ultimo_login,gastos_100d,peso,quantos_dias_sem_comer
0,1001,28,1,1200.0,110,1
1,1002,45,5,8500.0,68,2
2,1003,32,2,400.0,90,4
3,1004,19,0,NaN,62,3

[[1003, 30, 2, 400.0, 90, 4],
 [1002, 33, 5, 8500.0, 68, 2],
 [1001, 46, 1, 1200.0, 110, 1]]

In [ ]:
feature_vectors

[[32, 2, 400.0, 90, 4], [45, 5, 8500.0, 68, 2]]